import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from '@clerk/nextjs';
import Homepage from "@/components/Homepage";
import Navbar from "@/components/Navbar";
import { checkUser } from "@/lib/checkUser";
import DoctorSidebar from "@/components/DoctorSidebar";
import PatientSidebar from "@/components/PatientSidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const userData = await checkUser();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <SignedOut>
                  <Homepage />
                </SignedOut>
                <SignedIn>
                <div className="w-full z-50 bg-white shadow-md fixed h-12">
                  <Navbar />
                </div>
                <div className="flex min-h-[95vh]">
                  {userData?.role !== "ADMIN" && (
                    <div className="bg-white z-10 w-56 mt-12 h-screen fixed shadow-md hidden lg:block">
                      {userData?.role === "DOCTOR"?
                        <DoctorSidebar/>
                          :
                        <PatientSidebar/>
                      } 
                    </div>
                    )}
                    <div className={`w-full mt-12 sm:mb-0 p-2 ${userData?.role !== "ADMIN" ? "lg:ml-56" : "ml-10"}`}>
                      {children}
                    </div>
                  </div>
              </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
